### ISSUE TITLE
filter Pickups Only within a radius

### ISSUE THREAD

**Issue by Cebion** [Bastl34/eBayChangeListener#2]
Thanks for this wonderful project.
I've seen that you have a function to  filter Pickups Only.
There is no option to set this on the website so to include it in a search.
When I set this variable to true on what basis will it filter?,  on the whole country or is it possible to include a zip code 
to only show items near me

**Comment by Bastl34** [comment]
On `ebay.de` you can define a zip code and a max. radius for your search.  This is then encoded to the url.
But I have not found something similar on `ebay.com` 

`ebay.de` example url:
```
https://www.ebay.de/sch/i.html?_localstpos=10115&_fcid=77&_sadis=50&LH_Distance=2&_fspt=1&_fpos=10115&_clu=2&gbr=1&_stpos=10115&_from=R40&_sacat=0&_sop=10&_nkw=smartphone&_dcat=9355&LH_PrefLoc=0&rt=nc&LH_BIN=1
```

Zip: 10115
Radius: 50

What you can try is to rip out the url parameter and check if they are working on `ebay.com`

**Comment by Cebion** [comment]
Thanks a lot!
